version: '2'
services:
    ncmssec-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/ncmssec/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ncmssec
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
